export enum DayType {
  WORKING_DAY = 'WORKING_DAY',
  RESTRICTED_HOLIDAY = 'RESTRICTED_HOLIDAY',
  UNIVERSITY_HOLIDAY = 'UNIVERSITY_HOLIDAY',
  NO_CLASS_DAY = 'NO_CLASS_DAY',
  EXAM_DAY = 'EXAM_DAY',
  WEEKEND_DAY = 'WEEKEND_DAY',
}
